name: Publish to PyPI on Release

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5

      - name: Set up Python
        run: uv python install

      - name: Publish to PyPI
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}